#ifndef MANAGE_ALARM_IMPL_THERMOSTAT_MONITOR_TEMPERATURE_MANAGE_ALARM_H
#define MANAGE_ALARM_IMPL_THERMOSTAT_MONITOR_TEMPERATURE_MANAGE_ALARM_H

#include <all.h>

Unit isolette_Monitor_Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_initialise_(STACK_FRAME_ONLY);

Unit isolette_Monitor_Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_finalise_(STACK_FRAME_ONLY);

Unit isolette_Monitor_Manage_Alarm_impl_thermostat_monitor_temperature_manage_alarm_timeTriggered_(STACK_FRAME_ONLY);

#endif
