#ifndef TEMPERATURE_SENSOR_IMPL_TEMPERATURE_SENSOR_CPI_THERMOSTAT_H
#define TEMPERATURE_SENSOR_IMPL_TEMPERATURE_SENSOR_CPI_THERMOSTAT_H

#include <all.h>

Unit isolette_Devices_Temperature_Sensor_impl_temperature_sensor_cpi_thermostat_initialise_(STACK_FRAME_ONLY);

Unit isolette_Devices_Temperature_Sensor_impl_temperature_sensor_cpi_thermostat_finalise_(STACK_FRAME_ONLY);

Unit isolette_Devices_Temperature_Sensor_impl_temperature_sensor_cpi_thermostat_timeTriggered_(STACK_FRAME_ONLY);

#endif
