#ifndef MANAGE_MONITOR_INTERFACE_IMPL_THERMOSTAT_MONITOR_TEMPERATURE_MANAGE_MONITOR_INTERFACE_H
#define MANAGE_MONITOR_INTERFACE_IMPL_THERMOSTAT_MONITOR_TEMPERATURE_MANAGE_MONITOR_INTERFACE_H

#include <all.h>

Unit isolette_Monitor_Manage_Monitor_Interface_impl_thermostat_monitor_temperature_manage_monitor_interface_initialise_(STACK_FRAME_ONLY);

Unit isolette_Monitor_Manage_Monitor_Interface_impl_thermostat_monitor_temperature_manage_monitor_interface_finalise_(STACK_FRAME_ONLY);

Unit isolette_Monitor_Manage_Monitor_Interface_impl_thermostat_monitor_temperature_manage_monitor_interface_timeTriggered_(STACK_FRAME_ONLY);

#endif
