#ifndef MANAGE_MONITOR_INTERFACE_IMPL_THERMOSTAT_MONITOR_TEMPERATURE_MANAGE_MONITOR_INTERFACE_API_H
#define MANAGE_MONITOR_INTERFACE_IMPL_THERMOSTAT_MONITOR_TEMPERATURE_MANAGE_MONITOR_INTERFACE_API_H

#include <all.h>

// This file was auto-generated.  Do not edit

bool api_get_upper_alarm_tempWstatus__isolette_Monitor_Manage_Monitor_Interface_impl_thermostat_monitor_temperature_manage_monitor_interface(
  STACK_FRAME
  isolette_Isolette_Data_Model_TempWstatus_impl value);

bool api_get_lower_alarm_tempWstatus__isolette_Monitor_Manage_Monitor_Interface_impl_thermostat_monitor_temperature_manage_monitor_interface(
  STACK_FRAME
  isolette_Isolette_Data_Model_TempWstatus_impl value);

bool api_get_current_tempWstatus__isolette_Monitor_Manage_Monitor_Interface_impl_thermostat_monitor_temperature_manage_monitor_interface(
  STACK_FRAME
  isolette_Isolette_Data_Model_TempWstatus_impl value);

bool api_get_monitor_mode__isolette_Monitor_Manage_Monitor_Interface_impl_thermostat_monitor_temperature_manage_monitor_interface(
  STACK_FRAME
  isolette_Isolette_Data_Model_Monitor_Mode_Type *value);

void api_put_upper_alarm_temp__isolette_Monitor_Manage_Monitor_Interface_impl_thermostat_monitor_temperature_manage_monitor_interface(
  STACK_FRAME
  isolette_Isolette_Data_Model_Temp_impl value);

void api_put_lower_alarm_temp__isolette_Monitor_Manage_Monitor_Interface_impl_thermostat_monitor_temperature_manage_monitor_interface(
  STACK_FRAME
  isolette_Isolette_Data_Model_Temp_impl value);

void api_put_monitor_status__isolette_Monitor_Manage_Monitor_Interface_impl_thermostat_monitor_temperature_manage_monitor_interface(
  STACK_FRAME
  isolette_Isolette_Data_Model_Status_Type value);

void api_put_interface_failure__isolette_Monitor_Manage_Monitor_Interface_impl_thermostat_monitor_temperature_manage_monitor_interface(
  STACK_FRAME
  isolette_Isolette_Data_Model_Failure_Flag_impl value);

void api_logInfo__isolette_Monitor_Manage_Monitor_Interface_impl_thermostat_monitor_temperature_manage_monitor_interface(
  STACK_FRAME
  String str);

void api_logDebug__isolette_Monitor_Manage_Monitor_Interface_impl_thermostat_monitor_temperature_manage_monitor_interface(
  STACK_FRAME
  String str);

void api_logError__isolette_Monitor_Manage_Monitor_Interface_impl_thermostat_monitor_temperature_manage_monitor_interface(
  STACK_FRAME
  String str);

#endif
