#ifndef MANAGE_HEAT_SOURCE_IMPL_THERMOSTAT_REGULATE_TEMPERATURE_MANAGE_HEAT_SOURCE_H
#define MANAGE_HEAT_SOURCE_IMPL_THERMOSTAT_REGULATE_TEMPERATURE_MANAGE_HEAT_SOURCE_H

#include <all.h>

Unit isolette_Regulate_Manage_Heat_Source_impl_thermostat_regulate_temperature_manage_heat_source_initialise_(STACK_FRAME_ONLY);

Unit isolette_Regulate_Manage_Heat_Source_impl_thermostat_regulate_temperature_manage_heat_source_finalise_(STACK_FRAME_ONLY);

Unit isolette_Regulate_Manage_Heat_Source_impl_thermostat_regulate_temperature_manage_heat_source_timeTriggered_(STACK_FRAME_ONLY);

#endif
