#ifndef MANAGE_HEAT_SOURCE_IMPL_THERMOSTAT_REGULATE_TEMPERATURE_MANAGE_HEAT_SOURCE_API_H
#define MANAGE_HEAT_SOURCE_IMPL_THERMOSTAT_REGULATE_TEMPERATURE_MANAGE_HEAT_SOURCE_API_H

#include <all.h>

// This file was auto-generated.  Do not edit

bool api_get_current_tempWstatus__isolette_Regulate_Manage_Heat_Source_impl_thermostat_regulate_temperature_manage_heat_source(
  STACK_FRAME
  isolette_Isolette_Data_Model_TempWstatus_impl value);

bool api_get_lower_desired_temp__isolette_Regulate_Manage_Heat_Source_impl_thermostat_regulate_temperature_manage_heat_source(
  STACK_FRAME
  isolette_Isolette_Data_Model_Temp_impl value);

bool api_get_upper_desired_temp__isolette_Regulate_Manage_Heat_Source_impl_thermostat_regulate_temperature_manage_heat_source(
  STACK_FRAME
  isolette_Isolette_Data_Model_Temp_impl value);

bool api_get_regulator_mode__isolette_Regulate_Manage_Heat_Source_impl_thermostat_regulate_temperature_manage_heat_source(
  STACK_FRAME
  isolette_Isolette_Data_Model_Regulator_Mode_Type *value);

void api_put_heat_control__isolette_Regulate_Manage_Heat_Source_impl_thermostat_regulate_temperature_manage_heat_source(
  STACK_FRAME
  isolette_Isolette_Data_Model_On_Off_Type value);

void api_logInfo__isolette_Regulate_Manage_Heat_Source_impl_thermostat_regulate_temperature_manage_heat_source(
  STACK_FRAME
  String str);

void api_logDebug__isolette_Regulate_Manage_Heat_Source_impl_thermostat_regulate_temperature_manage_heat_source(
  STACK_FRAME
  String str);

void api_logError__isolette_Regulate_Manage_Heat_Source_impl_thermostat_regulate_temperature_manage_heat_source(
  STACK_FRAME
  String str);

#endif
