#ifndef MANAGE_REGULATOR_INTERFACE_IMPL_THERMOSTAT_REGULATE_TEMPERATURE_MANAGE_REGULATOR_INTERFACE_API_H
#define MANAGE_REGULATOR_INTERFACE_IMPL_THERMOSTAT_REGULATE_TEMPERATURE_MANAGE_REGULATOR_INTERFACE_API_H

#include <all.h>

// This file was auto-generated.  Do not edit

bool api_get_upper_desired_tempWstatus__isolette_Regulate_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface(
  STACK_FRAME
  isolette_Isolette_Data_Model_TempWstatus_impl value);

bool api_get_lower_desired_tempWstatus__isolette_Regulate_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface(
  STACK_FRAME
  isolette_Isolette_Data_Model_TempWstatus_impl value);

bool api_get_current_tempWstatus__isolette_Regulate_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface(
  STACK_FRAME
  isolette_Isolette_Data_Model_TempWstatus_impl value);

bool api_get_regulator_mode__isolette_Regulate_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface(
  STACK_FRAME
  isolette_Isolette_Data_Model_Regulator_Mode_Type *value);

void api_put_upper_desired_temp__isolette_Regulate_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface(
  STACK_FRAME
  isolette_Isolette_Data_Model_Temp_impl value);

void api_put_lower_desired_temp__isolette_Regulate_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface(
  STACK_FRAME
  isolette_Isolette_Data_Model_Temp_impl value);

void api_put_displayed_temp__isolette_Regulate_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface(
  STACK_FRAME
  isolette_Isolette_Data_Model_Temp_impl value);

void api_put_regulator_status__isolette_Regulate_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface(
  STACK_FRAME
  isolette_Isolette_Data_Model_Status_Type value);

void api_put_interface_failure__isolette_Regulate_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface(
  STACK_FRAME
  isolette_Isolette_Data_Model_Failure_Flag_impl value);

void api_logInfo__isolette_Regulate_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface(
  STACK_FRAME
  String str);

void api_logDebug__isolette_Regulate_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface(
  STACK_FRAME
  String str);

void api_logError__isolette_Regulate_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface(
  STACK_FRAME
  String str);

#endif
