#ifndef MANAGE_REGULATOR_INTERFACE_IMPL_THERMOSTAT_REGULATE_TEMPERATURE_MANAGE_REGULATOR_INTERFACE_H
#define MANAGE_REGULATOR_INTERFACE_IMPL_THERMOSTAT_REGULATE_TEMPERATURE_MANAGE_REGULATOR_INTERFACE_H

#include <all.h>

Unit isolette_Regulate_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface_initialise_(STACK_FRAME_ONLY);

Unit isolette_Regulate_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface_finalise_(STACK_FRAME_ONLY);

Unit isolette_Regulate_Manage_Regulator_Interface_impl_thermostat_regulate_temperature_manage_regulator_interface_timeTriggered_(STACK_FRAME_ONLY);

#endif
