// #Sireum

package tc.GUMBO_Definitions

import org.sireum._
import tc._

// this file is autogenerated, do not edit

object GUMBO__Library {
  @strictpure def absoluteZero(): Base_Types.Float_32 = -459.67f
}
