// #Sireum

package tc.TempSensor

import org.sireum._
import tc.GumboXUtil.GumboXResult
import tc.RandomLib
import org.sireum.Random.Gen64
import org.sireum.Random.Impl.Xoshiro256

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// Distribute SlangCheck test runners

@record class TempSensorPeriodic_p_tcproc_tempSensor_GumboX_DSC_TestRunner
  extends Random.Gen.TestRunner[TempSensorPeriodic_p_tcproc_tempSensor_PreState_Container_P]
  with TempSensorPeriodic_p_tcproc_tempSensor_GumboX_TestHarness {

  val verbose: B = F

  var seedGen: Gen64 = Random.Gen64Impl(Xoshiro256.create)

  override def next(): TempSensorPeriodic_p_tcproc_tempSensor_PreState_Container_P = {
    return TempSensorPeriodic_p_tcproc_tempSensor_PreState_Container_P(
    )
  }

  override def toCompactJson(o: TempSensorPeriodic_p_tcproc_tempSensor_PreState_Container_P): String = {
    return tc.JSON.fromTempSensorTempSensorPeriodic_p_tcproc_tempSensor_PreState_Container_P(o, T)
  }

  override def fromJson(json: String): TempSensorPeriodic_p_tcproc_tempSensor_PreState_Container_P = {
    tc.JSON.toTempSensorTempSensorPeriodic_p_tcproc_tempSensor_PreState_Container_P(json) match {
      case Either.Left(o) => return o
      case Either.Right(msg) => halt(msg.string)
    }
  }

  override def test(o: TempSensorPeriodic_p_tcproc_tempSensor_PreState_Container_P): B = {
    BeforeEntrypoint()
    val r: B = testComputeCBV(o) match {
      case GumboXResult.Pre_Condition_Unsat =>
        tc.DSC_RecordUnsatPre.report(tc.JSON.fromTempSensorTempSensorPeriodic_p_tcproc_tempSensor_PreState_Container_P(o, T))
        T
      case GumboXResult.Post_Condition_Fail => F
      case GumboXResult.Post_Condition_Pass => T
    }
    AfterEntrypoint()
    return r
  }
}
