// #Sireum

package tc.TempSensor

import org.sireum._
import tc.RandomLib

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// Profile for initialise entrypoint
@record class TempSensorPeriodic_p_tcproc_tempSensor_Profile (
  val name: String,
  val numTests: Z //number of tests to generate
)

// Profile with generators for incoming ports
@record class TempSensorPeriodic_p_tcproc_tempSensor_Profile_P(
  val name: String,
  val numTests: Z, // number of tests to generate
  var numTestVectorGenRetries: Z, // number of test vector generation retries
  )

// Profile with generators for state variables and incoming ports
@record class TempSensorPeriodic_p_tcproc_tempSensor_Profile_PS(
  val name: String,
  val numTests: Z, // number of tests to generate
  var numTestVectorGenRetries: Z, // number of test vector generation retries
  )
