// #Sireum

package tc.TempSensor

import org.sireum._
import art._
import tc.SystemTestSuiteSlang.runtimeMonitorStream
import tc._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object TempSensorPeriodic_p_tcproc_tempSensor_SystemTestAPI {
  /** helper method to set the values of all incoming ports
    */
  def put_concrete_inputs(): Unit = {
  }



  def fetchContainer(): tc.TempSensor.TempSensorPeriodic_p_tcproc_tempSensor_PostState_Container_PS = {
    if (runtimeMonitorStream.contains(Arch.TempControlSoftwareSystem_p_Instance_tcproc_tempSensor.id)) {
      val (_, postContainer_) = runtimeMonitorStream.get(Arch.TempControlSoftwareSystem_p_Instance_tcproc_tempSensor.id).get
      return postContainer_.asInstanceOf[tc.TempSensor.TempSensorPeriodic_p_tcproc_tempSensor_PostState_Container_PS]
    }
    else {
      assert(F, s"No post state recorded for ${Arch.TempControlSoftwareSystem_p_Instance_tcproc_tempSensor.name}")
      halt(s"No post state recorded for ${Arch.TempControlSoftwareSystem_p_Instance_tcproc_tempSensor.name}")
    }
  }

  def check_concrete_outputs(api_currentTemp: TempSensor.Temperature_i): Unit = {
    var failureReasons: ISZ[ST] = ISZ()

    val actual_currentTemp = get_api_currentTemp()
    if (api_currentTemp != actual_currentTemp) {
      failureReasons = failureReasons :+ st"'currentTemp' did not match expected.  Expected: $api_currentTemp, Actual: $actual_currentTemp"
    }

    assert(failureReasons.isEmpty, st"${(failureReasons, "\n")}".render)
  }

  def get_api_currentTemp(): TempSensor.Temperature_i = {
    return fetchContainer().api_currentTemp
  }
}