// #Sireum
package tc.TempControlSoftwareSystem

import org.sireum._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@msig trait TempControl_s_tcproc_tempControl_Injection_Provider {
  def pre_receiveInput(): Unit
}

object TempControl_s_tcproc_tempControl_Injection_Service {

  var providers: MSZ[TempControl_s_tcproc_tempControl_Injection_Provider] = MSZ()

  def register(provider: TempControl_s_tcproc_tempControl_Injection_Provider): Unit = {
    providers = providers :+ provider
  }

  def pre_receiveInput(): Unit = {
    for (provider <- providers) {
      provider.pre_receiveInput()
    }
  }
}