// #Sireum

package tc.CoolingFan

import org.sireum._
import tc._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@enum object FanAck {
  "Ok"
  "Error"
}

object FanAck_Payload {
  def example(): FanAck_Payload = {
    return FanAck_Payload(CoolingFan.FanAck.byOrdinal(0).get)
  }
}

@datatype class FanAck_Payload(value: CoolingFan.FanAck.Type) extends art.DataContent
