// #Sireum
package isolette.Devices

import org.sireum._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@msig trait Temperature_Sensor_impl_temperature_sensor_cpi_thermostat_Injection_Provider {
  def pre_receiveInput(): Unit
}

object Temperature_Sensor_impl_temperature_sensor_cpi_thermostat_Injection_Service {

  var providers: MSZ[Temperature_Sensor_impl_temperature_sensor_cpi_thermostat_Injection_Provider] = MSZ()

  def register(provider: Temperature_Sensor_impl_temperature_sensor_cpi_thermostat_Injection_Provider): Unit = {
    providers = providers :+ provider
  }

  def pre_receiveInput(): Unit = {
    for (provider <- providers) {
      provider.pre_receiveInput()
    }
  }
}