#ifndef DETECT_REGULATOR_FAILURE_IMPL_THERMOSTAT_REGULATE_TEMPERATURE_DETECT_REGULATOR_FAILURE_H
#define DETECT_REGULATOR_FAILURE_IMPL_THERMOSTAT_REGULATE_TEMPERATURE_DETECT_REGULATOR_FAILURE_H

#include <all.h>

Unit isolette_Regulate_Detect_Regulator_Failure_impl_thermostat_regulate_temperature_detect_regulator_failure_initialise_(STACK_FRAME_ONLY);

Unit isolette_Regulate_Detect_Regulator_Failure_impl_thermostat_regulate_temperature_detect_regulator_failure_finalise_(STACK_FRAME_ONLY);

Unit isolette_Regulate_Detect_Regulator_Failure_impl_thermostat_regulate_temperature_detect_regulator_failure_timeTriggered_(STACK_FRAME_ONLY);

#endif
