// #Sireum

package tc.TempControlSoftwareSystem

import org.sireum._
import art._
import tc._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object TempControl_s_tcproc_tempControl_EntryPoint_Companion {

  var preStateContainer_wL: Option[TempControl_s_tcproc_tempControl_PreState_wLContainer] = None()

  def pre_initialise(): Unit = {
    // assume/require contracts cannot refer to incoming ports or
    // state variables so nothing to do here
  }

  def post_initialise(): Unit = {
    // block the component while its post-state values are retrieved
    val postStateContainer_wL =
      TempControl_s_tcproc_tempControl_PostState_wLContainer(
        currentFanState = tc.TempControlSoftwareSystem.TempControl_s_tcproc_tempControl.currentFanState,
        currentSetPoint = tc.TempControlSoftwareSystem.TempControl_s_tcproc_tempControl.currentSetPoint,
        latestTemp = tc.TempControlSoftwareSystem.TempControl_s_tcproc_tempControl.latestTemp,
        api_fanCmd = 
          if (Art.observeOutPortVariable(Arch.TempControlSoftwareSystem_s_Instance_tcproc_tempControl.operational_api.fanCmd_Id).nonEmpty)
            Some(Art.observeOutPortVariable(Arch.TempControlSoftwareSystem_s_Instance_tcproc_tempControl.operational_api.fanCmd_Id).get.asInstanceOf[CoolingFan.FanCmd_Payload].value)
          else None())

    // the rest can now be performed via a different thread
    tc.runtimemonitor.RuntimeMonitor.observePostState(Arch.TempControlSoftwareSystem_s_Instance_tcproc_tempControl.id, tc.runtimemonitor.ObservationKind.tempControl_postInit, postStateContainer_wL)
  }

  def pre_compute(): Unit = {
    // block the component while its pre-state values are retrieved
    preStateContainer_wL = Some(
      TempControl_s_tcproc_tempControl_PreState_wLContainer(
        In_currentFanState = tc.TempControlSoftwareSystem.TempControl_s_tcproc_tempControl.currentFanState, 
        In_currentSetPoint = tc.TempControlSoftwareSystem.TempControl_s_tcproc_tempControl.currentSetPoint, 
        In_latestTemp = tc.TempControlSoftwareSystem.TempControl_s_tcproc_tempControl.latestTemp, 
        api_tempChanged = Art.observeInPortVariable(Arch.TempControlSoftwareSystem_s_Instance_tcproc_tempControl.operational_api.tempChanged_Id).asInstanceOf[Option[art.Empty]], 
        api_fanAck = 
          if (Art.observeInPortVariable(Arch.TempControlSoftwareSystem_s_Instance_tcproc_tempControl.operational_api.fanAck_Id).nonEmpty)
            Some(Art.observeInPortVariable(Arch.TempControlSoftwareSystem_s_Instance_tcproc_tempControl.operational_api.fanAck_Id).get.asInstanceOf[CoolingFan.FanAck_Payload].value)
          else None(), 
        api_setPoint = 
          if (Art.observeInPortVariable(Arch.TempControlSoftwareSystem_s_Instance_tcproc_tempControl.operational_api.setPoint_Id).nonEmpty)
            Some(Art.observeInPortVariable(Arch.TempControlSoftwareSystem_s_Instance_tcproc_tempControl.operational_api.setPoint_Id).get.asInstanceOf[TempControlSoftwareSystem.SetPoint_i_Payload].value)
          else None(), 
        api_currentTemp = Art.observeInPortVariable(Arch.TempControlSoftwareSystem_s_Instance_tcproc_tempControl.operational_api.currentTemp_Id).get.asInstanceOf[TempSensor.Temperature_i_Payload].value))

    // the rest can now be performed via a different thread
    tc.runtimemonitor.RuntimeMonitor.observePreState(Arch.TempControlSoftwareSystem_s_Instance_tcproc_tempControl.id, tc.runtimemonitor.ObservationKind.tempControl_preCompute, preStateContainer_wL.asInstanceOf[Option[art.DataContent]])
  }

  def post_compute(): Unit = {
    // block the component while its post-state values are retrieved
    val postStateContainer_wL =
      TempControl_s_tcproc_tempControl_PostState_wLContainer(
        currentFanState = tc.TempControlSoftwareSystem.TempControl_s_tcproc_tempControl.currentFanState,
        currentSetPoint = tc.TempControlSoftwareSystem.TempControl_s_tcproc_tempControl.currentSetPoint,
        latestTemp = tc.TempControlSoftwareSystem.TempControl_s_tcproc_tempControl.latestTemp,
        api_fanCmd = 
          if (Art.observeOutPortVariable(Arch.TempControlSoftwareSystem_s_Instance_tcproc_tempControl.operational_api.fanCmd_Id).nonEmpty)
            Some(Art.observeOutPortVariable(Arch.TempControlSoftwareSystem_s_Instance_tcproc_tempControl.operational_api.fanCmd_Id).get.asInstanceOf[CoolingFan.FanCmd_Payload].value)
          else None())

    // the rest can now be performed via a different thread
    tc.runtimemonitor.RuntimeMonitor.observePrePostState(Arch.TempControlSoftwareSystem_s_Instance_tcproc_tempControl.id, tc.runtimemonitor.ObservationKind.tempControl_postCompute, preStateContainer_wL.asInstanceOf[Option[art.DataContent]], postStateContainer_wL)
  }
}