// #Sireum

package tc

import org.sireum._
import art._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object LegacyDemo extends App {
  def main(args: ISZ[String]): Z = {

    val seed: Z = if (args.size == z"1") {
      val n = Z(args(0)).get
      if (n <= z"0") 1 else n
    } else {
      1
    }

    PlatformComm.initialise(seed, None())

    val empty = art.Empty()

    PlatformComm.sendAsync(IPCPorts.TempSensor_s_tcproc_tempSensor_App, IPCPorts.TempSensor_s_tcproc_tempSensor_App, empty)
    PlatformComm.sendAsync(IPCPorts.Fan_s_tcproc_fan_App, IPCPorts.Fan_s_tcproc_fan_App, empty)
    PlatformComm.sendAsync(IPCPorts.TempControl_s_tcproc_tempControl_App, IPCPorts.TempControl_s_tcproc_tempControl_App, empty)
    PlatformComm.sendAsync(IPCPorts.OperatorInterface_s_tcproc_operatorInterface_App, IPCPorts.OperatorInterface_s_tcproc_operatorInterface_App, empty)

    PlatformComm.finalise()
    return 0
  }
}
