#ifndef HEAT_SOURCE_IMPL_HEAT_SOURCE_CPI_HEAT_CONTROLLER_H
#define HEAT_SOURCE_IMPL_HEAT_SOURCE_CPI_HEAT_CONTROLLER_H

#include <all.h>

Unit isolette_Devices_Heat_Source_impl_heat_source_cpi_heat_controller_initialise_(STACK_FRAME_ONLY);

Unit isolette_Devices_Heat_Source_impl_heat_source_cpi_heat_controller_finalise_(STACK_FRAME_ONLY);

Unit isolette_Devices_Heat_Source_impl_heat_source_cpi_heat_controller_timeTriggered_(STACK_FRAME_ONLY);

#endif
