// #Sireum

package isolette.Isolette_Data_Model

import org.sireum._
import isolette._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object Temp_impl {
  def example(): Isolette_Data_Model.Temp_impl = {
    return Isolette_Data_Model.Temp_impl(
      value = Base_Types.Float_32_example())
  }
}

@datatype class Temp_impl(
  val value: F32) {
}

object Temp_impl_Payload {
  def example(): Temp_impl_Payload = {
    return Temp_impl_Payload(Isolette_Data_Model.Temp_impl.example())
  }
}

@datatype class Temp_impl_Payload(value: Isolette_Data_Model.Temp_impl) extends art.DataContent
