// #Sireum
package isolette.Isolette

import org.sireum._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@msig trait operator_interface_thread_impl_operator_interface_oip_oit_Injection_Provider {
  def pre_receiveInput(): Unit
}

object operator_interface_thread_impl_operator_interface_oip_oit_Injection_Service {

  var providers: MSZ[operator_interface_thread_impl_operator_interface_oip_oit_Injection_Provider] = MSZ()

  def register(provider: operator_interface_thread_impl_operator_interface_oip_oit_Injection_Provider): Unit = {
    providers = providers :+ provider
  }

  def pre_receiveInput(): Unit = {
    for (provider <- providers) {
      provider.pre_receiveInput()
    }
  }
}