// #Sireum

package tc.CoolingFan

import org.sireum._
import tc.RandomLib

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// Profile with generators for incoming ports
@record class FanPeriodic_p_tcproc_fan_Profile_P(
  val name: String,
  val numTests: Z, // number of tests to generate
  var api_fanCmd: RandomLib)

// Profile with generators for state variables and incoming ports
@record class FanPeriodic_p_tcproc_fan_Profile_PS(
  val name: String,
  val numTests: Z, // number of tests to generate
  var api_fanCmd: RandomLib)
