// #Sireum

package tc.CoolingFan

import org.sireum._
import tc._
import tc.GumboXUtil.GumboXResult

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
@msig trait FanPeriodic_p_tcproc_fan_GumboX_TestHarness extends FanPeriodic_p_tcproc_fan_TestApi {
  /** Contract-based test harness for the compute entry point
    * @param api_fanCmd incoming data port
    */
  def testComputeCB(
      api_fanCmd: CoolingFan.FanCmd.Type): GumboXResult.Type = {
    // [SaveInLocal]: retrieve and save the current (input) values of GUMBO-declared local state variables as retrieved from the component state
    //   fan does not have incoming ports or state variables

    // [CheckPre]: check/filter based on pre-condition.
    //   fan's compute entry point does not have top level assume clauses

    // [PutInPorts]: put values on the input ports
    put_fanCmd(api_fanCmd)

    // [InvokeEntryPoint]: invoke the entry point test method
    testCompute()

    // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
    //   fan does not have outgoing ports or state variables

    // [CheckPost]: invoke the oracle function
    //   fan does not contain guarantee clauses for its compute entrypoint

    return GumboXResult.Post_Condition_Pass
  }
}
