// #Sireum

package RTS.Actuation

import org.sireum._
import RTS._
import RTS.GumboXUtil.GumboXResult

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
@msig trait Actuator_i_actuationSubsystem_saturationActuatorUnit_saturationActuator_actuator_GumboX_TestHarness extends Actuator_i_actuationSubsystem_saturationActuatorUnit_saturationActuator_actuator_TestApi {
  /** Contract-based test harness for the initialise entry point
    */
  def testInitialiseCB(
      ): GumboXResult.Type = {
    // [InvokeEntryPoint]: invoke the entry point test method
    testInitialise()

    // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
    val api_output: Base_Types.Boolean = get_output().get

    // [CheckPost]: invoke the oracle function
    val postResult = RTS.Actuation.Actuator_i_actuationSubsystem_saturationActuatorUnit_saturationActuator_actuator_GumboX.inititialize_IEP_Post(api_output)
    if (!postResult) {
      return GumboXResult.Post_Condition_Fail
    }

    return GumboXResult.Post_Condition_Pass
  }

  /** Contract-based test harness for the compute entry point
    * @param api_input incoming data port
    * @param api_manualActuatorInput incoming data port
    */
  def testComputeCB(
      api_input: Base_Types.Boolean,
      api_manualActuatorInput: Base_Types.Boolean): GumboXResult.Type = {
    // [SaveInLocal]: retrieve and save the current (input) values of GUMBO-declared local state variables as retrieved from the component state
    //   actuator does not have incoming ports or state variables

    // [CheckPre]: check/filter based on pre-condition.
    //   actuator's compute entry point does not have top level assume clauses

    // [PutInPorts]: put values on the input ports
    put_input(api_input)
    put_manualActuatorInput(api_manualActuatorInput)

    // [InvokeEntryPoint]: invoke the entry point test method
    testCompute()

    // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
    val api_output: Base_Types.Boolean = get_output().get

    // [CheckPost]: invoke the oracle function
    val postResult = RTS.Actuation.Actuator_i_actuationSubsystem_saturationActuatorUnit_saturationActuator_actuator_GumboX.compute_CEP_Post(api_input, api_manualActuatorInput, api_output)
    if (!postResult) {
      return GumboXResult.Post_Condition_Fail
    }

    return GumboXResult.Post_Condition_Pass
  }
}
