// #Sireum

package RTS.Actuation

import org.sireum._
import RTS.RandomLib

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// Profile for initialise entrypoint
@record class Actuator_i_actuationSubsystem_tempPressureActuatorUnit_tempPressureActuator_actuator_Profile (
  val name: String,
  val numTests: Z //number of tests to generate
)

// Profile with generators for incoming ports
@record class Actuator_i_actuationSubsystem_tempPressureActuatorUnit_tempPressureActuator_actuator_Profile_P(
  val name: String,
  val numTests: Z, // number of tests to generate
  var numTestVectorGenRetries: Z, // number of test vector generation retries
  var api_input: RandomLib,
  var api_manualActuatorInput: RandomLib)

// Profile with generators for state variables and incoming ports
@record class Actuator_i_actuationSubsystem_tempPressureActuatorUnit_tempPressureActuator_actuator_Profile_PS(
  val name: String,
  val numTests: Z, // number of tests to generate
  var numTestVectorGenRetries: Z, // number of test vector generation retries
  var api_input: RandomLib,
  var api_manualActuatorInput: RandomLib)
