// #Sireum

package isolette.runtimemonitor

import org.sireum._
import isolette._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@enum object ObservationKind {
  "manage_regulator_interface_postInit"
  "manage_regulator_interface_preCompute"
  "manage_regulator_interface_postCompute"
  "manage_heat_source_postInit"
  "manage_heat_source_preCompute"
  "manage_heat_source_postCompute"
  "manage_regulator_mode_postInit"
  "manage_regulator_mode_preCompute"
  "manage_regulator_mode_postCompute"
  "manage_monitor_interface_postInit"
  "manage_monitor_interface_preCompute"
  "manage_monitor_interface_postCompute"
  "manage_alarm_postInit"
  "manage_alarm_preCompute"
  "manage_alarm_postCompute"
  "manage_monitor_mode_postInit"
  "manage_monitor_mode_preCompute"
  "manage_monitor_mode_postCompute"
}
