#ifndef MANAGE_MONITOR_MODE_IMPL_THERMOSTAT_MONITOR_TEMPERATURE_MANAGE_MONITOR_MODE_H
#define MANAGE_MONITOR_MODE_IMPL_THERMOSTAT_MONITOR_TEMPERATURE_MANAGE_MONITOR_MODE_H

#include <all.h>

Unit isolette_Monitor_Manage_Monitor_Mode_impl_thermostat_monitor_temperature_manage_monitor_mode_initialise_(STACK_FRAME_ONLY);

Unit isolette_Monitor_Manage_Monitor_Mode_impl_thermostat_monitor_temperature_manage_monitor_mode_finalise_(STACK_FRAME_ONLY);

Unit isolette_Monitor_Manage_Monitor_Mode_impl_thermostat_monitor_temperature_manage_monitor_mode_timeTriggered_(STACK_FRAME_ONLY);

#endif
