// #Sireum

package tc.TempSensor

import org.sireum._
import tc._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// Test vector containers for Distributed SlangCheck testing

@datatype class TempSensorPeriodic_p_tcproc_tempSensor_DSC_TestVector (
  )
