// #Sireum

package tc.TempSensor

import org.sireum._
import tc._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// containers for the pre and post state values of ports and state variables

@sig trait TempSensorPeriodic_p_tcproc_tempSensor_PreState_Container extends art.DataContent {
}

// container for incoming ports
@datatype class TempSensorPeriodic_p_tcproc_tempSensor_PreState_Container_P (
  ) extends TempSensorPeriodic_p_tcproc_tempSensor_PreState_Container

// container for incoming ports and state variables
@datatype class TempSensorPeriodic_p_tcproc_tempSensor_PreState_Container_PS (
  ) extends TempSensorPeriodic_p_tcproc_tempSensor_PreState_Container

@sig trait TempSensorPeriodic_p_tcproc_tempSensor_PostState_Container extends art.DataContent {
  def api_currentTemp: TempSensor.Temperature_i
}

// container for outgoing ports
@datatype class TempSensorPeriodic_p_tcproc_tempSensor_PostState_Container_P (
  val api_currentTemp: TempSensor.Temperature_i) extends TempSensorPeriodic_p_tcproc_tempSensor_PostState_Container

// container for outgoing ports and state variables
@datatype class TempSensorPeriodic_p_tcproc_tempSensor_PostState_Container_PS (
  val api_currentTemp: TempSensor.Temperature_i) extends TempSensorPeriodic_p_tcproc_tempSensor_PostState_Container
