#ifndef DETECT_MONITOR_FAILURE_IMPL_THERMOSTAT_MONITOR_TEMPERATURE_DETECT_MONITOR_FAILURE_H
#define DETECT_MONITOR_FAILURE_IMPL_THERMOSTAT_MONITOR_TEMPERATURE_DETECT_MONITOR_FAILURE_H

#include <all.h>

Unit isolette_Monitor_Detect_Monitor_Failure_impl_thermostat_monitor_temperature_detect_monitor_failure_initialise_(STACK_FRAME_ONLY);

Unit isolette_Monitor_Detect_Monitor_Failure_impl_thermostat_monitor_temperature_detect_monitor_failure_finalise_(STACK_FRAME_ONLY);

Unit isolette_Monitor_Detect_Monitor_Failure_impl_thermostat_monitor_temperature_detect_monitor_failure_timeTriggered_(STACK_FRAME_ONLY);

#endif
