#ifndef DETECT_MONITOR_FAILURE_IMPL_THERMOSTAT_MONITOR_TEMPERATURE_DETECT_MONITOR_FAILURE_API_H
#define DETECT_MONITOR_FAILURE_IMPL_THERMOSTAT_MONITOR_TEMPERATURE_DETECT_MONITOR_FAILURE_API_H

#include <all.h>

// This file was auto-generated.  Do not edit

void api_put_internal_failure__isolette_Monitor_Detect_Monitor_Failure_impl_thermostat_monitor_temperature_detect_monitor_failure(
  STACK_FRAME
  isolette_Isolette_Data_Model_Failure_Flag_impl value);

void api_logInfo__isolette_Monitor_Detect_Monitor_Failure_impl_thermostat_monitor_temperature_detect_monitor_failure(
  STACK_FRAME
  String str);

void api_logDebug__isolette_Monitor_Detect_Monitor_Failure_impl_thermostat_monitor_temperature_detect_monitor_failure(
  STACK_FRAME
  String str);

void api_logError__isolette_Monitor_Detect_Monitor_Failure_impl_thermostat_monitor_temperature_detect_monitor_failure(
  STACK_FRAME
  String str);

#endif
