#include <Detect_Monitor_Failure_impl_thermostat_monitor_temperature_detect_monitor_failure_api.h>
#include <Detect_Monitor_Failure_impl_thermostat_monitor_temperature_detect_monitor_failure.h>
#include <ext.h>

// This file will not be overwritten so is safe to edit

static char* component_id = "isolette_single_sensor_Instance_thermostat_monitor_temperature_detect_monitor_failure";

Unit isolette_Monitor_Detect_Monitor_Failure_impl_thermostat_monitor_temperature_detect_monitor_failure_initialise_(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "Detect_Monitor_Failure_impl_thermostat_monitor_temperature_detect_monitor_failure.c", "", "isolette_Monitor_Detect_Monitor_Failure_impl_thermostat_monitor_temperature_detect_monitor_failure_initialise_", 0);

  printf("%s: isolette_Monitor_Detect_Monitor_Failure_impl_thermostat_monitor_temperature_detect_monitor_failure_initialise_ called\n", component_id);

  // example usage of api setters

  DeclNewisolette_Isolette_Data_Model_Failure_Flag_impl(t0);
  isolette_Isolette_Data_Model_Failure_Flag_impl_example(SF &t0);
  api_put_internal_failure__isolette_Monitor_Detect_Monitor_Failure_impl_thermostat_monitor_temperature_detect_monitor_failure(SF &t0);

  /* example usage of api loggers. Commented out as the constructed String may be too long
  api_logInfo__isolette_Monitor_Detect_Monitor_Failure_impl_thermostat_monitor_temperature_detect_monitor_failure(SF string("Example logInfo"));

  api_logDebug__isolette_Monitor_Detect_Monitor_Failure_impl_thermostat_monitor_temperature_detect_monitor_failure(SF string("Example logDebug"));

  api_logError__isolette_Monitor_Detect_Monitor_Failure_impl_thermostat_monitor_temperature_detect_monitor_failure(SF string("Example logError"));
  */
}

Unit isolette_Monitor_Detect_Monitor_Failure_impl_thermostat_monitor_temperature_detect_monitor_failure_finalise_(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "Detect_Monitor_Failure_impl_thermostat_monitor_temperature_detect_monitor_failure.c", "", "isolette_Monitor_Detect_Monitor_Failure_impl_thermostat_monitor_temperature_detect_monitor_failure_finalise_", 0);
}

Unit isolette_Monitor_Detect_Monitor_Failure_impl_thermostat_monitor_temperature_detect_monitor_failure_timeTriggered_(STACK_FRAME_ONLY) {
  DeclNewStackFrame(caller, "Detect_Monitor_Failure_impl_thermostat_monitor_temperature_detect_monitor_failure.c", "", "isolette_Monitor_Detect_Monitor_Failure_impl_thermostat_monitor_temperature_detect_monitor_failure_timeTriggered_", 0);

}
