#ifndef MANAGE_REGULATOR_MODE_IMPL_THERMOSTAT_REGULATE_TEMPERATURE_MANAGE_REGULATOR_MODE_H
#define MANAGE_REGULATOR_MODE_IMPL_THERMOSTAT_REGULATE_TEMPERATURE_MANAGE_REGULATOR_MODE_H

#include <all.h>

Unit isolette_Regulate_Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_initialise_(STACK_FRAME_ONLY);

Unit isolette_Regulate_Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_finalise_(STACK_FRAME_ONLY);

Unit isolette_Regulate_Manage_Regulator_Mode_impl_thermostat_regulate_temperature_manage_regulator_mode_timeTriggered_(STACK_FRAME_ONLY);

#endif
