#ifndef OPERATOR_INTERFACE_THREAD_IMPL_OPERATOR_INTERFACE_OIP_OIT_H
#define OPERATOR_INTERFACE_THREAD_IMPL_OPERATOR_INTERFACE_OIP_OIT_H

#include <all.h>

Unit isolette_Isolette_operator_interface_thread_impl_operator_interface_oip_oit_initialise_(STACK_FRAME_ONLY);

Unit isolette_Isolette_operator_interface_thread_impl_operator_interface_oip_oit_finalise_(STACK_FRAME_ONLY);

Unit isolette_Isolette_operator_interface_thread_impl_operator_interface_oip_oit_timeTriggered_(STACK_FRAME_ONLY);

#endif
