// #Sireum

package RTS.Actuation

import org.sireum._
import RTS._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// Test vector containers for Distributed SlangCheck testing

@datatype class Actuator_i_actuationSubsystem_saturationActuatorUnit_saturationActuator_actuator_DSC_TestVector (
  val api_input: B,
  val api_manualActuatorInput: B)
