// #Sireum

package RTS.Actuation

import org.sireum._
import RTS._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// Test vector containers for Distributed SlangCheck testing

@datatype class OrLogic_i_actuationSubsystem_actuationUnit2_tempPressureTripOut_orLogic_DSC_TestVector (
  val api_channel1: B,
  val api_channel2: B)
