// #Sireum

package tc.TempControlSoftwareSystem

import org.sireum._
import tc._
import tc.GumboXUtil.GumboXResult

// Do not edit this file as it will be overwritten if HAMR codegen is rerun
@msig trait OperatorInterfacePeriodic_p_tcproc_operatorInterface_GumboX_TestHarness extends OperatorInterfacePeriodic_p_tcproc_operatorInterface_TestApi {
  /** Contract-based test harness for the initialise entry point
    */
  def testInitialiseCB(
      ): GumboXResult.Type = {
    // [InvokeEntryPoint]: invoke the entry point test method
    testInitialise()

    // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
    val api_setPoint: TempControlSoftwareSystem.SetPoint_i = get_setPoint().get

    // [CheckPost]: invoke the oracle function
    val postResult = tc.TempControlSoftwareSystem.OperatorInterfacePeriodic_p_tcproc_operatorInterface_GumboX.inititialize_IEP_Post(api_setPoint)
    if (!postResult) {
      return GumboXResult.Post_Condition_Fail
    }

    return GumboXResult.Post_Condition_Pass
  }

  /** Contract-based test harness for the compute entry point
    * @param api_currentTemp incoming data port
    */
  def testComputeCB(
      api_currentTemp: TempSensor.Temperature_i): GumboXResult.Type = {
    // [SaveInLocal]: retrieve and save the current (input) values of GUMBO-declared local state variables as retrieved from the component state
    //   operatorInterface does not have incoming ports or state variables

    // [CheckPre]: check/filter based on pre-condition.
    val CEP_Pre_Result: B = tc.TempControlSoftwareSystem.OperatorInterfacePeriodic_p_tcproc_operatorInterface_GumboX.compute_CEP_Pre (api_currentTemp)
    if (!CEP_Pre_Result) {
      return GumboXResult.Pre_Condition_Unsat
    }

    // [PutInPorts]: put values on the input ports
    put_currentTemp(api_currentTemp)

    // [InvokeEntryPoint]: invoke the entry point test method
    testCompute()

    // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
    val api_setPoint: TempControlSoftwareSystem.SetPoint_i = get_setPoint().get

    // [CheckPost]: invoke the oracle function
    val postResult = tc.TempControlSoftwareSystem.OperatorInterfacePeriodic_p_tcproc_operatorInterface_GumboX.compute_CEP_Post(api_setPoint)
    if (!postResult) {
      return GumboXResult.Post_Condition_Fail
    }

    return GumboXResult.Post_Condition_Pass
  }
}
