// #Sireum

package tc.TempControlSoftwareSystem

import org.sireum._
import tc.GumboXUtil.GumboXResult
import tc.RandomLib
import org.sireum.Random.Gen64
import org.sireum.Random.Impl.Xoshiro256

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

// Distribute SlangCheck test runners

@record class OperatorInterfacePeriodic_p_tcproc_operatorInterface_GumboX_DSC_TestRunner
  extends Random.Gen.TestRunner[OperatorInterfacePeriodic_p_tcproc_operatorInterface_PreState_Container_P]
  with OperatorInterfacePeriodic_p_tcproc_operatorInterface_GumboX_TestHarness {

  val verbose: B = F

  var seedGen: Gen64 = Random.Gen64Impl(Xoshiro256.create)
  val ranLibcurrentTemp: RandomLib = RandomLib(Random.Gen64Impl(Xoshiro256.createSeed(seedGen.genU64())))

  override def next(): OperatorInterfacePeriodic_p_tcproc_operatorInterface_PreState_Container_P = {
    val api_currentTemp = ranLibcurrentTemp.nextTempSensorTemperature_i()
    return OperatorInterfacePeriodic_p_tcproc_operatorInterface_PreState_Container_P(
      api_currentTemp
    )
  }

  override def toCompactJson(o: OperatorInterfacePeriodic_p_tcproc_operatorInterface_PreState_Container_P): String = {
    return tc.JSON.fromTempControlSoftwareSystemOperatorInterfacePeriodic_p_tcproc_operatorInterface_PreState_Container_P(o, T)
  }

  override def fromJson(json: String): OperatorInterfacePeriodic_p_tcproc_operatorInterface_PreState_Container_P = {
    tc.JSON.toTempControlSoftwareSystemOperatorInterfacePeriodic_p_tcproc_operatorInterface_PreState_Container_P(json) match {
      case Either.Left(o) => return o
      case Either.Right(msg) => halt(msg.string)
    }
  }

  override def test(o: OperatorInterfacePeriodic_p_tcproc_operatorInterface_PreState_Container_P): B = {
    BeforeEntrypoint()
    val r: B = testComputeCBV(o) match {
      case GumboXResult.Pre_Condition_Unsat =>
        tc.DSC_RecordUnsatPre.report(tc.JSON.fromTempControlSoftwareSystemOperatorInterfacePeriodic_p_tcproc_operatorInterface_PreState_Container_P(o, T))
        T
      case GumboXResult.Post_Condition_Fail => F
      case GumboXResult.Post_Condition_Pass => T
    }
    AfterEntrypoint()
    return r
  }
}
