// #Sireum
package tc.runtimemonitor

import org.sireum._
import tc._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object ModelInfo {
  val TempSensorPeriodic_p_tcproc_tempSensor_MI : Component =
    Component(
      name = "TempSensorPeriodic_p_tcproc_tempSensor",
      id = Arch.TempControlSoftwareSystem_p_Instance_tcproc_tempSensor.id.toZ,
      dispatchProtocol = iDispatchProtocol.Periodic,
      state = ISZ(
        Port(
          name = "currentTemp",
          id = Arch.TempControlSoftwareSystem_p_Instance_tcproc_tempSensor.currentTemp.id.toZ,
          kind = PortKind.Data,
          direction = StateDirection.Out,
          slangType = "")))

  val FanPeriodic_p_tcproc_fan_MI : Component =
    Component(
      name = "FanPeriodic_p_tcproc_fan",
      id = Arch.TempControlSoftwareSystem_p_Instance_tcproc_fan.id.toZ,
      dispatchProtocol = iDispatchProtocol.Periodic,
      state = ISZ(
        Port(
          name = "fanCmd",
          id = Arch.TempControlSoftwareSystem_p_Instance_tcproc_fan.fanCmd.id.toZ,
          kind = PortKind.Data,
          direction = StateDirection.In,
          slangType = ""),
        Port(
          name = "fanAck",
          id = Arch.TempControlSoftwareSystem_p_Instance_tcproc_fan.fanAck.id.toZ,
          kind = PortKind.Data,
          direction = StateDirection.Out,
          slangType = "")))

  val TempControlPeriodic_p_tcproc_tempControl_MI : Component =
    Component(
      name = "TempControlPeriodic_p_tcproc_tempControl",
      id = Arch.TempControlSoftwareSystem_p_Instance_tcproc_tempControl.id.toZ,
      dispatchProtocol = iDispatchProtocol.Periodic,
      state = ISZ(
        StateVariable(
          name = "In_latestFanCmd",
          id = 0,
          direction = StateDirection.In,
          slangType = "CoolingFan.FanCmd.Type"),
        StateVariable(
          name = "latestFanCmd",
          id = 0,
          direction = StateDirection.Out,
          slangType = "CoolingFan.FanCmd.Type"),
        Port(
          name = "currentTemp",
          id = Arch.TempControlSoftwareSystem_p_Instance_tcproc_tempControl.currentTemp.id.toZ,
          kind = PortKind.Data,
          direction = StateDirection.In,
          slangType = ""),
        Port(
          name = "fanAck",
          id = Arch.TempControlSoftwareSystem_p_Instance_tcproc_tempControl.fanAck.id.toZ,
          kind = PortKind.Data,
          direction = StateDirection.In,
          slangType = ""),
        Port(
          name = "setPoint",
          id = Arch.TempControlSoftwareSystem_p_Instance_tcproc_tempControl.setPoint.id.toZ,
          kind = PortKind.Data,
          direction = StateDirection.In,
          slangType = ""),
        Port(
          name = "fanCmd",
          id = Arch.TempControlSoftwareSystem_p_Instance_tcproc_tempControl.fanCmd.id.toZ,
          kind = PortKind.Data,
          direction = StateDirection.Out,
          slangType = "")))

  val OperatorInterfacePeriodic_p_tcproc_operatorInterface_MI : Component =
    Component(
      name = "OperatorInterfacePeriodic_p_tcproc_operatorInterface",
      id = Arch.TempControlSoftwareSystem_p_Instance_tcproc_operatorInterface.id.toZ,
      dispatchProtocol = iDispatchProtocol.Periodic,
      state = ISZ(
        Port(
          name = "currentTemp",
          id = Arch.TempControlSoftwareSystem_p_Instance_tcproc_operatorInterface.currentTemp.id.toZ,
          kind = PortKind.Data,
          direction = StateDirection.In,
          slangType = ""),
        Port(
          name = "setPoint",
          id = Arch.TempControlSoftwareSystem_p_Instance_tcproc_operatorInterface.setPoint.id.toZ,
          kind = PortKind.Data,
          direction = StateDirection.Out,
          slangType = "")))

  val modelInfo: ModelInfo =
    ModelInfo(ISZ(
     TempSensorPeriodic_p_tcproc_tempSensor_MI,
     FanPeriodic_p_tcproc_fan_MI,
     TempControlPeriodic_p_tcproc_tempControl_MI,
     OperatorInterfacePeriodic_p_tcproc_operatorInterface_MI))
}

@datatype class ModelInfo(val components: ISZ[Component])

@datatype class Component(val name: String,
                          val id: Z,
                          val dispatchProtocol: iDispatchProtocol.Type,
                          val state: ISZ[StateElement])

@enum object iDispatchProtocol {
  "Sporadic"
  "Periodic"
}

@enum object StateDirection {
  "In"
  "Out"
}

@sig trait StateElement {
  def name: String

  def id: Z

  def slangType: String

  def direction: StateDirection.Type
}

@enum object PortKind {
  "Data"
  "Event"
  "EventData"
}

@datatype class Port(val name: String,
                     val id: Z,
                     val kind: PortKind.Type,
                     val direction: StateDirection.Type,
                     val slangType: String) extends StateElement

@datatype class StateVariable(val name: String,
                              val id: Z,
                              val direction: StateDirection.Type,
                              val slangType: String) extends StateElement
