// #Sireum

package tc.TempSensor

import org.sireum._
import tc._

// this file is autogenerated, do not edit

object GUMBO__Library {
  @strictpure def inRange(temp: TempSensor.Temperature_i): Base_Types.Boolean = temp.degrees >= -50.0f &&
    temp.degrees <= 150.0f
}
