// #Sireum

package tc.GUMBO_Definitions

import org.sireum._
import tc._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object GUMBO__Library {
  @strictpure def absoluteZero(): Base_Types.Float_32 = -459.67f
}
